---
- hosts: all
  pre_tasks:

    - name: Docker | Enable doc installation in yum
      lineinfile:
        path: /etc/yum.conf
        regexp: '^tsflags=nodocs'
        state: absent
      become: true

    - debug:
        var: ansible_facts

  roles:
    - {role: zabbix-server-deploy,
       zabbix_url: "172.17.0.2"}
